drop table if exists articles cascade ;
drop table if exists countries cascade ;
drop table if exists employee_orders cascade ;
drop table if exists employees cascade ;
drop table if exists order_items cascade ;
drop table if exists orders cascade ;
drop table if exists suppliers cascade ;
drop sequence if exists articles_seq;
drop sequence if exists countries_seq;
drop sequence if exists employees_seq;
drop sequence if exists orders_seq;
drop sequence if exists suppliers_seq;
drop table if exists articles cascade ;
drop table if exists countries cascade ;
drop table if exists employee_orders cascade ;
drop table if exists employees cascade ;
drop table if exists order_items cascade ;
drop table if exists orders cascade ;
drop table if exists suppliers cascade ;
drop sequence if exists articles_seq;
drop sequence if exists countries_seq;
drop sequence if exists employees_seq;
drop sequence if exists orders_seq;
drop sequence if exists suppliers_seq;
