set
client_min_messages = WARNING;
alter table if exists employees drop constraint if exists FK_supplier_country;
alter table if exists order_items drop constraint if exists FK_order_item_article;
alter table if exists order_items drop constraint if exists FK_order_item_order;
alter table if exists orders drop constraint if exists FK_order_employee;
alter table if exists orders drop constraint if exists FK_order_supplier;
alter table if exists suppliers drop constraint if exists FK_supplier_country;
drop table if exists articles cascade;
drop table if exists countries cascade;
drop table if exists employees cascade;
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists suppliers cascade;
drop sequence if exists articles_seq;
drop sequence if exists countries_seq;
drop sequence if exists employees_seq;
drop sequence if exists orders_seq;
drop sequence if exists suppliers_seq;
set
client_min_messages = WARNING;
alter table if exists employees drop constraint if exists FK_supplier_country;
alter table if exists order_items drop constraint if exists FK_order_item_article;
alter table if exists order_items drop constraint if exists FK_order_item_order;
alter table if exists orders drop constraint if exists FK_order_employee;
alter table if exists orders drop constraint if exists FK_order_supplier;
alter table if exists suppliers drop constraint if exists FK_supplier_country;
drop table if exists articles cascade;
drop table if exists countries cascade;
drop table if exists employees cascade;
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists suppliers cascade;
drop sequence if exists articles_seq;
drop sequence if exists countries_seq;
drop sequence if exists employees_seq;
drop sequence if exists orders_seq;
drop sequence if exists suppliers_seq;
set
client_min_messages = WARNING;
alter table if exists employees drop constraint if exists FK_supplier_country;
alter table if exists order_items drop constraint if exists FK_order_item_article;
alter table if exists order_items drop constraint if exists FK_order_item_order;
alter table if exists orders drop constraint if exists FK_order_employee;
alter table if exists orders drop constraint if exists FK_order_supplier;
alter table if exists suppliers drop constraint if exists FK_supplier_country;
drop table if exists articles cascade;
drop table if exists countries cascade;
drop table if exists employees cascade;
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists suppliers cascade;
drop sequence if exists articles_seq;
drop sequence if exists countries_seq;
drop sequence if exists employees_seq;
drop sequence if exists orders_seq;
drop sequence if exists suppliers_seq;
set
client_min_messages = WARNING;
alter table if exists employees drop constraint if exists FK_supplier_country;
alter table if exists order_items drop constraint if exists FK_order_item_article;
alter table if exists order_items drop constraint if exists FK_order_item_order;
alter table if exists orders drop constraint if exists FK_order_employee;
alter table if exists orders drop constraint if exists FK_order_supplier;
alter table if exists suppliers drop constraint if exists FK_supplier_country;
drop table if exists articles cascade;
drop table if exists countries cascade;
drop table if exists employees cascade;
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists suppliers cascade;
drop sequence if exists articles_seq;
drop sequence if exists countries_seq;
drop sequence if exists employees_seq;
drop sequence if exists orders_seq;
drop sequence if exists suppliers_seq;
set
client_min_messages = WARNING;
alter table if exists employees drop constraint if exists FK_supplier_country;
alter table if exists order_items drop constraint if exists FK_order_item_article;
alter table if exists order_items drop constraint if exists FK_order_item_order;
alter table if exists orders drop constraint if exists FK_order_employee;
alter table if exists orders drop constraint if exists FK_order_supplier;
alter table if exists suppliers drop constraint if exists FK_supplier_country;
drop table if exists articles cascade;
drop table if exists countries cascade;
drop table if exists employees cascade;
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists suppliers cascade;
drop sequence if exists articles_seq;
drop sequence if exists countries_seq;
drop sequence if exists employees_seq;
drop sequence if exists orders_seq;
drop sequence if exists suppliers_seq;
set
client_min_messages = WARNING;
alter table if exists employees drop constraint if exists FK_supplier_country;
alter table if exists order_items drop constraint if exists FK_order_item_article;
alter table if exists order_items drop constraint if exists FK_order_item_order;
alter table if exists orders drop constraint if exists FK_order_employee;
alter table if exists orders drop constraint if exists FK_order_supplier;
alter table if exists suppliers drop constraint if exists FK_supplier_country;
drop table if exists articles cascade;
drop table if exists countries cascade;
drop table if exists employees cascade;
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists suppliers cascade;
drop sequence if exists articles_seq;
drop sequence if exists countries_seq;
drop sequence if exists employees_seq;
drop sequence if exists orders_seq;
drop sequence if exists suppliers_seq;
set
client_min_messages = WARNING;
alter table if exists employees drop constraint if exists FK_supplier_country;
alter table if exists order_items drop constraint if exists FK_order_item_article;
alter table if exists order_items drop constraint if exists FK_order_item_order;
alter table if exists orders drop constraint if exists FK_order_employee;
alter table if exists orders drop constraint if exists FK_order_supplier;
alter table if exists suppliers drop constraint if exists FK_supplier_country;
drop table if exists articles cascade;
drop table if exists countries cascade;
drop table if exists employees cascade;
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists suppliers cascade;
drop sequence if exists articles_seq;
drop sequence if exists countries_seq;
drop sequence if exists employees_seq;
drop sequence if exists orders_seq;
drop sequence if exists suppliers_seq;
set
client_min_messages = WARNING;
alter table if exists employees drop constraint if exists FK_supplier_country;
alter table if exists order_items drop constraint if exists FK_order_item_article;
alter table if exists order_items drop constraint if exists FK_order_item_order;
alter table if exists orders drop constraint if exists FK_order_employee;
alter table if exists orders drop constraint if exists FK_order_supplier;
alter table if exists suppliers drop constraint if exists FK_supplier_country;
drop table if exists articles cascade;
drop table if exists countries cascade;
drop table if exists employees cascade;
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists suppliers cascade;
drop sequence if exists articles_seq;
drop sequence if exists countries_seq;
drop sequence if exists employees_seq;
drop sequence if exists orders_seq;
drop sequence if exists suppliers_seq;
set
client_min_messages = WARNING;
alter table if exists employees drop constraint if exists FK_supplier_country;
alter table if exists order_items drop constraint if exists FK_order_item_article;
alter table if exists order_items drop constraint if exists FK_order_item_order;
alter table if exists orders drop constraint if exists FK_order_employee;
alter table if exists orders drop constraint if exists FK_order_supplier;
alter table if exists suppliers drop constraint if exists FK_supplier_country;
drop table if exists articles cascade;
drop table if exists countries cascade;
drop table if exists employees cascade;
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists suppliers cascade;
drop sequence if exists articles_seq;
drop sequence if exists countries_seq;
drop sequence if exists employees_seq;
drop sequence if exists orders_seq;
drop sequence if exists suppliers_seq;
